# Generated by Django 2.2.6 on 2019-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='category.Category')),
            ],
        ),
    ]
